export let years = [
  {
    year: 2006,
    //photos: ['fotos/2008/01.jpg', 'fotos/2008/01.jpg', 'fotos/2008/01.jpg'],
    photos: [
      { url: "fotos/2011/05.jpg", date: "Febrero( Maquilladita )" },
      { url: "fotos/2008/01.jpg", date: "15/11/06" },
      { url: "fotos/2008/01.jpg", date: "15/11/06" },
    ],
    text: "",
  },
  {
    year: 2007,
    photos: [
      { url: "fotos/2008/01.jpg", date: "Junio" },
      { url: "fotos/2008/02.jpg", date: "Octubre (ya usando la PC)" },
    ],
    text: "",
  },
  {
    year: 2008,
    photos: [
      { url: "fotos/2008/01.jpg", date: "Junio" },
      { url: "fotos/2008/02.jpg", date: "Octubre (ya usando la PC)" },
      { url: "fotos/2008/03.jpg", date: "Octubre (Con su hermanita...)" },
      { url: "fotos/2008/04.jpg", date: "Noviembre" },
      { url: "fotos/2008/05.jpg", date: "Diciembre, en la pile" },
      { url: "fotos/2008/06.jpg", date: "Diciembre" },
    ],
    text: "",
  },
  {
    year: 2009,
    photos: [
      { url: "fotos/2009/00.jpg", date: "Febrero( Cumpliendo 3 )" },
      { url: "fotos/2009/01.jpg", date: "Septiembre( Pensativa )" },
      { url: "fotos/2009/02.jpg", date: "Septiembre" },
      { url: "fotos/2009/09.jpg", date: "Agosto( Maquillada )" },
      { url: "fotos/2009/03.jpg", date: "Octubre( Topless?? )" },
      { url: "fotos/2009/02.jpg", date: "Octubre" },
      { url: "fotos/2009/05.jpg", date: "Diciembre" },
      { url: "fotos/2009/06.jpg", date: "Diciembre(Sonrisita)" },
      { url: "fotos/2009/07.jpg", date: "Diciembre( Ojitos )" },
      { url: "fotos/2009/08.jpg", date: "Diciembre( Ella con la tia )" },
    ],
    text: "",
  },
  {
    year: 2010,
    photos: [
      { url: "fotos/2010/01.jpg", date: "Enero" },
      { url: "fotos/2010/02.jpg", date: "Enero" },
      { url: "fotos/2010/06.jpg", date: "Enero" },
      { url: "fotos/2010/03.jpg", date: "Noviembre" },
      { url: "fotos/2010/05.jpg", date: "Noviembre" },
      { url: "fotos/2010/04.jpg", date: "Diciembre( Mariposa )" },
    ],
    text: "",
  },
  {
    year: 2011,
    photos: [
      { url: "fotos/2011/04.jpg", date: "Febrero" },
      { url: "fotos/2011/05.jpg", date: "Febrero( Maquilladita )" },
      { url: "fotos/2011/06.jpg", date: "Febrero( Vamos al Jardin )" },
      { url: "fotos/2011/01.jpg", date: "Mayo( Con el hermanito)" },
      { url: "fotos/2011/02.jpg", date: "Junio( Con Mama )" },
      { url: "fotos/2011/03.jpg", date: "Julio" },
      { url: "fotos/2011/07.jpg", date: "Agosto( La PC ... )" },
      { url: "fotos/2011/08.jpg", date: "Septiembre( Esperando ? )" },
      { url: "fotos/2011/09.jpg", date: "Septiembre( Facha )" },
    ],
    text: "",
  },
  {
    year: 2012,
    photos: [
      { url: "fotos/2012/01.jpg", date: "Septiembre( A las Corridas )" },
      { url: "fotos/2012/02.jpg", date: "Septiembre( Cabalgando )" },
    ],
    text: "",
  },
  {
    year: 2013,
    photos: [{ url: "fotos/2013/01.jpg", date: "Septiembre( Que corte! )" }],
    text: "",
  },
  {
    year: 2014,
    photos: [
      { url: "fotos/2014/01.jpg", date: "Julio( Con los hermanitos )" },
      { url: "fotos/2014/02.jpg", date: "Julio( Con los hermanitos x2 )" },
      { url: "fotos/2014/03.jpg", date: "Agosto( Cuando comia pizza!)" },
      { url: "fotos/2014/04.jpg", date: "Agosto" },
      { url: "fotos/2014/05.jpg", date: "Noviembre( Con sus hermanos )" },
      { url: "fotos/2014/06.jpg", date: "Diciembre" },
      { url: "fotos/2014/07.jpg", date: "Diciembre( De ninera )" },
    ],
    text: "",
  },
  {
    year: 2015,
    photos: [
      { url: "fotos/2015/01.jpg", date: "Marzo" },
      { url: "fotos/2015/02.jpg", date: "Junio( Jura de la bandera )" },
      { url: "fotos/2015/03.jpg", date: "Junio( Jura de la bandera )" },
      { url: "fotos/2015/04.jpg", date: "Julio( Posando )" },
      { url: "fotos/2015/05.jpg", date: "Julio( Que juntaaa!!! )" },
      { url: "fotos/2015/06.jpg", date: "Julio" },
      { url: "fotos/2015/07.jpg", date: "Septiembre" },
      { url: "fotos/2015/08.jpg", date: "Septiembre" },
    ],
    text: "",
  },
  {
    year: 2016,
    photos: [],
    text: "",
  },
  {
    year: 2017,
    photos: [],
    text: "",
  },
  {
    year: 2018,
    photos: [],
    text: "",
  },
  {
    year: 2019,
    photos: [],
    text: "",
  },
  {
    year: 2020,
    photos: [],
    text: "",
  },
  {
    year: 2021,
    photos: [],
    text: "",
  },
];
